name: CI_CD_testunit
on:
  push:
    branches: 
      - dev
jobs:
  testunit:

    runs-on: ubuntu_latest
    
    strategy:
      matrix:
        version: ["16", "18"]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - name: get dependencies
        run: npm install

      - name: run test
        run: npm test
