name: CI_CD_all

on:
  push:
    branches: [ "main" ]

jobs:
  testunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["16", "18"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: get dependencies
        run: npm install

      - name: run test
        run: npm test

      - name: audit
        run: npm audit
      
  analyse:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep:1.74.0
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3

      - name: "Execute semgrep" 
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default

      - name: "Upload SARIF file GitHub CodeQL"
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif

  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/3dvp:latest
   
  trivy:
    name: Trivy 
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep:1.74.0
    steps:
      - name: "Run trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/3dvp:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: "Upload trivy scan results" 
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
