# name: CI_CD_testunit
# on:
#   pull_request:
#     branches: ["main"]
# jobs:
#   analyzesecu:
#     strategy:
#       matrix:
#         version: ["16", "18"]

#     runs-on: ubuntu_latest
  
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.version }}

#       - name: get dependencies
#         run: npm install

#       - name: run test
#         run: npm test

#       - name: analyse code eslint
#         run: eslint .

#       - name: analyse code prettier
#         run: prettier --check '**/*.{js,jsx,ts,tsx,json,css,scss,md}'

#       - name: audit
#         run: npm audit --audit-level=high

#       - name: Setup Semgrep
#         run: pip install semgrep

#       - name: Analyse Semgrep
#         run: semgrep --config auto
      
name: CI_CD_analyze

on:
  pull_request:
    branches: [ "main" ]

jobs:
  testunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["16", "18"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: get dependencies
        run: npm install

      - name: run test
        run: npm test

      - name: audit
        run: npm audit --audit-level=high
      
      - name: Setup Semgrep
        run: pip install semgrep

      - name: Analyse Semgrep
        run: semgrep --config auto